
## DB config goes here
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:mem:puppyDb
    username: sa
    password: sa
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ##      ddl-auto: update
      ddl-auto: create
    defer-datasource-initialization: true

## Logging settings
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR